pipeline:
  publish:
    image: plugins/docker
    repo: registry.thegraveyard.org/blurringexistence.net
    dockerfile: Dockerfile
    registry: registry.thegraveyard.org
    secrets: [docker_username, docker_password]
    when:
      branch: master

  deploy:
    image: plugins/webhook
    secrets: [webhook_username, webhook_password]
    urls: https://deploy.thegraveyard.org/
    when:
      branch: master
